name: 🚀 (DEV) Liberando versiones

on:
    push:
        branches:
            - builderbot-dev

jobs:
    ############ RELEASE ############
    build:
        name: Build DEV
        runs-on: ubuntu-latest
        outputs:
            commit: ${{ steps.vars.outputs.commit }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  ref: ${{github.event.after}}
                  persist-credentials: false

            - uses: pnpm/action-setup@v2.2.4
              with:
                  version: 9.0.6

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 22.20.0
                  cache: 'pnpm'
                  registry-url: https://registry.npmjs.org/

            - run: corepack enable

            - name: Install NPM Dependencies
              run: pnpm install --frozen-lockfile

            - name: Build Package
              run: pnpm build:full

            - name: Release Alpha
              run: npx lerna publish --canary --preid alpha --dist-tag alpha --yes
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
